name: "Chrome Extension Release"

on:
  push:
    tags:
      - 'chrome-v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: "Build and Release Chrome Extension"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chrome-extension
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: chrome-extension/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Extract version from tag and sync to package.json
        id: sync_version
        shell: bash
        run: |
          TAG="${GITHUB_REF##*/}"
          VERSION="${TAG#chrome-v}"
          echo "Tag: $TAG"
          echo "Parsed version: $VERSION"
          if [[ ! "$VERSION" =~ ^[0-9]+(\.[0-9]+){2,3}$ ]]; then
            echo "Invalid version format for Chrome (expect x.y.z or x.y.z.w): $VERSION"
            exit 1
          fi
          npm version "$VERSION" --no-git-tag-version --allow-same-version
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build the extension
        run: npm run build

      - name: Package the extension into a zip artifact
        run: npm run package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Chrome Extension v${{ steps.sync_version.outputs.version }}
          body: |
            ## LinkEveryWord Chrome Extension v${{ steps.sync_version.outputs.version }}

            This is an automated release of the LinkEveryWord Chrome Extension.
          draft: false
          prerelease: false
          files: chrome-extension/build/chrome-mv3-prod.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
